### ISSUE TITLE
VIsland - Workshop Automation - Choices made in the plugin are selected wrongly (ask for "A", get "B", maybe "C" if we're feeling spicy.)

### ISSUE THREAD

**Issue by Nox13last** [awgil/ffxiv_visland#1]
(Crossposted from https://github.com/awgil/ffxiv_plugin_distribution/issues/2. It was late and I was tired. Sorry about that.)

Great concept. I'm sick of having to fill one workshop out, create a Preset, assign the other workshops that preset, and then delete the preset. This would be a perfect solution (outside of getting Teamcraft to just press the buttons for me, too). Except, as of the recent Dalamud update (earlier today), the projects that are loaded into the workshop are not those that were selected.
Here's an example of the discrepancy: "Barbut" applied to all Workshops results in "Pie".

![image](https://github.com/awgil/ffxiv_plugin_distribution/assets/1292492/39848ad2-d70f-4caa-893d-3d0152432aa3)

I was going to do a table of "here's what I told it to insert" versus "what it inserted" (in case it was an item ID desync, or something), but there doesn't seem to be a pattern. Sometimes the _Rope_ will produce a _Rope_, and sometimes it will produce a _Salt Cod_. The _Potion_ will produce a _Sauerkraut_. _Garnet Rapier_ produces an _Iron Axe_. _Baked Pumpkin_ also produces _Sauerkraut_. Now the _Rope_ is producing _Sauerkraut_. Jam is _Dried Flowers_. Now the _Rope_ is _Dried Flowers_. 

I think when it brings up the "Set Agenda" UI, it's not swapping categories properly before it inserts what it thinks is an acceptable option. While everything I've tested is always wrong, _Rope_ in particular seems to copy whatever was inserted prior. _Potion_ always produces _Sauerkraut_, but _Rope_ is a beast of chaos.

I know this is also out of the scale of the ticket, but for what it's worth, the other part of the plugin (the gathering pather) works **splendidly**. I wish I had it back when I was grinding up to Sanctuary Rank 16 - I had to get to the top of the True Peak (where the rocks are), and make do with Cammy (to pull the FOV way out, so the "get nearest interactive target" button worked better) and a macro that executed "_lockon nearest target, cast 'Sprint', run and jump at it, wait a second, then interact, wait another second (to stop swinging the sledgehammer); loop all of that until I wake up_". There were just enough rocks up there that as soon as you mined the last one, the first one would respawn, and you could chase the route in circles and always have _one_ target to chase.
Can you add a function to import and export the pathing data for sharing? That'd be sick.
![image](https://github.com/awgil/ffxiv_plugin_distribution/assets/1292492/f307e50f-4cf4-4811-91fb-1028677c0134)

**Comment by awgil** [comment]
Can you verify that you group recipes by time rather than by category? Plugin currently assumes former.

**Comment by Nox13last** [comment]
I group recipes according to Category. Teamcraft's workshop planner specifies what categories a project can be found in - because it attempts to optimise Groove more than the value of the project at the time.
Looks like, this, FYI:
![image](https://github.com/awgil/ffxiv_visland/assets/1292492/23a339de-79f8-47a3-8a20-74b844ca0ca0)
It's easier to look through a small drawer labeled "Confections" (that has only six items) than to look through a humongous drawer that has 24 items, in my opinion.

On a preliminary investigation, setting it to Sort by Time" makes the problem go away.
![image](https://github.com/awgil/ffxiv_visland/assets/1292492/af897b78-62c5-429a-9dca-73d4efbb1814)

If all it'll take to get the plugin working in the meantime is to set it back to time grouping, then I'm cool with that - there's a search bar now. But the plugin malfunctioning with no clear cause is hardly ideal.

**Comment by awgil** [comment]
Yep, it's literally a beta I've just recently hacked up :D

**Comment by Nox13last** [comment]
Word.
I hope this ticket gives you something to work with, if you intend to continue development.
You can close the ticket when you're done with it. I'm satisfied that the plugin will do what I need it to.

**Comment by awgil** [comment]
Fixed the issue in v2: now it will automatically select correct grouping (by time), so that correct items are added.

Also implemented the suggestion about route import/export: there are now buttons to both export route into clipboard, and create new route based on clipboard contents (this is a simple json containing waypoints).
