### ISSUE TITLE
Underwater gathering when node is not next to you results in character moving downwards towards the floor

### ISSUE THREAD

**Issue by Otaku-2** [awgil/ffxiv_visland#10]
This happens with coordinates set from both "Move to current position" and "Interact with target"

If the Y coordinate is edited, it results in the buggy vertical movement others have mentioned with mounts

**Comment by awgil** [comment]
Should be fixed in the new version - I've reworked the way I do movement. Please reopen with more details if it turns out to be still reproducible.
