### ISSUE TITLE
[Feature Request] Separating the Mounting feature from the Jumping feature

### ISSUE THREAD

**Issue by joshboston723** [awgil/ffxiv_visland#11]
title

**Comment by awgil** [comment]
Can you clarify what do you mean? You want to mount up, but not jump (to avoid flying)? Or you want to jump without mounting (why?)?

**Comment by joshboston723** [comment]
To mount without jumping. 

When I tried it last time (before making this topic) it just spam jumped without actually flying.

**Comment by zbee** [comment]
Additionally, if you do not yet have flying, it just spams jump as you run around on your mount the whole time. This is at least annoying, would be nice to be able to turn it off.

**Comment by ar3ea** [comment]
also i want to add something too, when the character try to use mount the plugin already decide to move the character before the castbar even finished so it will fail to use the mount and bcs of that, plugin keep trying to use the mount again and do the same thing again until it got lucky and get mounted and continue like normal. maybe alittle bit delay or condition check can solved this issue.

**Comment by awgil** [comment]
Added no-flying movement mode.
