### ISSUE TITLE
[Bug] "Executing ##" does not match the ## step you clicked

### ISSUE THREAD

**Issue by zbee** [awgil/ffxiv_visland#12]
There is an off-by-1 error in the step number presented at the top of the plugin ("Executing: ... ###") and the actual step number in the route ("###: [...]")

Shown here in this truncated image, I clicked to execute only step 19, and it shows 18 at the top. This is consistent if you select to only run one step or a whole route

![image](https://github.com/awgil/ffxiv_visland/assets/1582821/8db05d5c-8e26-4c1d-b03f-16d8fd928ed3)

**Comment by awgil** [comment]
Thanks for the PR, merged.
