### ISSUE TITLE
API8 Version

### ISSUE THREAD

**Issue by CeleborWang** [awgil/ffxiv_visland#20]
Could you please provide an API8 version? Because CN version is still in 6.4 and cannot install the newest API9, thanks!

**Comment by McVaxius** [comment]
just check out an older version

**Comment by Rodboi** [comment]
麻烦问一下你找到了吗？请问哪个版本是API8版本的，怎么导入？谢谢

**Comment by CeleborWang** [comment]
找到了，比较早的版本，但用起来还可以，要怎么给你？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "awgil/ffxiv_visland"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月26日(星期四) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [awgil/ffxiv_visland] API8 Version (Issue #20)





 
麻烦问一下你找到了吗？请问哪个版本是API8版本的，怎么导入？谢谢

**Comment by Rodboi** [comment]
可以发到我QQ邮箱里吗？顺便问一下没有dll如何导入呀？我的QQ邮箱是2726157630@qq.com

**Comment by Rodboi** [comment]
非常感谢！麻烦发到我163邮箱里，邮箱号是heshaoxing9@163.com

**Comment by yomiyue** [comment]
你好，我也想要这个旧版本，希望能发送到我的邮箱yomi2310538430@gmail.com，非常感谢！

**Comment by CeleborWang** [comment]
> 你好，我也想要这个旧版本，希望能发送到我的邮箱[yomi2310538430@gmail.com](mailto:yomi2310538430@gmail.com)，非常感谢！

被判定为垃圾邮件退回了（

**Comment by yomiyue** [comment]
> > 你好，我也想要这个旧版本，希望能发送到我的邮箱[yomi2310538430@gmail.com](mailto:yomi2310538430@gmail.com)，非常感谢！
> 
> 被判定为垃圾邮件退回了（

实在是不好意思希望能再尝试一下163邮箱，邮箱号：xiarike17066@163.com

**Comment by Kooord** [comment]
> 找到了，比较早的版本，但用起来还可以，要怎么给你？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "awgil/ffxiv_visland" ***@***.***&gt;; 发送时间:&nbsp;2023年10月26日(星期四) 上午9:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [awgil/ffxiv_visland] API8 Version (Issue #20) 麻烦问一下你找到了吗？请问哪个版本是API8版本的，怎么导入？谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

你好，我也想要这个旧版本，希望能发送到我的邮箱fangmengdi297292@163.com，非常感谢！

**Comment by Kooord** [comment]
Okay, thank you very much for your reply！！










At 2023-11-02 05:12:02, "awgil" ***@***.***> wrote:

I appreciate y'all trying to get the working CN version, but github issues is not the appropriate place for exchanging emails and figuring this stuff out :)

I don't directly support CN version, since I don't have access to it, sorry. It's unfortunate that you are using old dalamud, I think the best way would be to go to the dalamud discord and discuss better strategy of version updates with them.

**Comment by Anti-World** [comment]
> 找到了，比较早的版本，但用起来还可以，要怎么给你？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "awgil/ffxiv_visland" ***@***.***&gt;; 发送时间:&nbsp;2023年10月26日(星期四) 上午9:56 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [awgil/ffxiv_visland] API8 Version (Issue #20) 麻烦问一下你找到了吗？请问哪个版本是API8版本的，怎么导入？谢谢 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

大佬也请发我一份，感谢
961882196@qq.com
