### ISSUE TITLE
Workshoper importer imported into rest day

### ISSUE THREAD

**Issue by xKiisa** [awgil/ffxiv_visland#21]
Trying to figure out the import plugin for favors and I was a bit confused because this week and next week was greyed out (I think because the discord bot doesn't specify a day) so I clicked on single day C0 which is my rest day and it seems to have added something to it but I can't check it nor cancel it since the rest day can't be accessed. I do see though that i got a couple materials allocated for today's cycle which shouldn't be possible
![00-15-02](https://github.com/awgil/ffxiv_visland/assets/104528108/c0bc8b5c-b0ec-4605-b913-820e42b20352)
![00-15-35](https://github.com/awgil/ffxiv_visland/assets/104528108/602a501d-f062-4521-83ff-920b16064d10)

Edit: I did indeed get a small amount of cowries from this

![11-57-50](https://github.com/awgil/ffxiv_visland/assets/104528108/41809996-9add-4a75-8af4-c3719eea448b)

**Comment by awgil** [comment]
This and all other ways to set invalid rest days should be fixed in the new version.
