### ISSUE TITLE
Updating repository breaks Sanctuary Automation other mods

### ISSUE THREAD

**Issue by Kadengt** [awgil/ffxiv_visland#27]
As title states, updating the repository breaks other mods. Boss Mod is one, and leaving the old repository allows the plugin(s) to still work. 

I did follow directions, uninstalled, re-installed, restarted the game, reset / reload data. None of it worked with the new url, but does with old. Unsure if I am doing something else wrong or not.

**Comment by Taurenkey** [comment]
This is ultimately an issue with Dalamud being pretty strict about the repo plugins come from. 

The only solution is to uninstall all plugins from the old repo and reinstall from the new, you won't lose settings.

**Comment by Kadengt** [comment]
> This is ultimately an issue with Dalamud being pretty strict about the repo plugins come from.
> 
> The only solution is to uninstall all plugins from the old repo and reinstall from the new, you won't lose settings.

Gotcha, Thank you :)
