### ISSUE TITLE
Workshop automation error: Error: Failed to import schedule: 0 items matching row ':OC_IsleberryJam: Isleberry Jam (6h)' and Error: Failed to import schedule: 0 items matching row ':OC_IslefishPie: Islefish Pie (6h)': 

### ISSUE THREAD

**Issue by ramblinguy** [awgil/ffxiv_visland#29]
Tried copying the workshop Fortune-Telling recommendations, but received an error `Error: Failed to import schedule: 0 items matching row ':OC_IsleberryJam: Isleberry Jam (6h)':`. In addition, when I tried to do the Favors, I also got the error `Error: Failed to import schedule: 0 items matching row ':OC_IslefishPie: Islefish Pie (6h)': `.

What I did as a workaround is to copy the recs into a text editor and manually remove the "Islefish", so that 
```
Cycle 4
First 3 Workshops
:OC_Butter: Butter (4h)
:OC_TomatoRelish: Tomato Relish (4h)
:OC_IsleberryJam: Isleberry Jam (6h)
:OC_Butter: Butter (4h)
:OC_IsleberryJam: Isleberry Jam (6h)
```
became
```
Cycle 4
First 3 Workshops
:OC_Butter: Butter (4h)
:OC_TomatoRelish: Tomato Relish (4h)
:OC_IsleberryJam: Jam (6h)
:OC_Butter: Butter (4h)
:OC_IsleberryJam: Jam (6h)
```

And the seemed to work. Similarly for Islefish Pie. This leads me to believe that maybe some text matching or parsing is erroring out specifically for Isleberry and Islefish?

Also, here's what the bot returned for my favors, with Islefish Pie, for testing if you need it:
```
Season 64 (Nov 7 - 13) Personalized Favor Schedules
Schedule #1
:OC_PopotoSalad: Popoto Salad (4h)
:OC_BoiledEgg: Boiled Egg (4h)
:OC_PopotoSalad: Popoto Salad (4h)
:OC_BoiledEgg: Boiled Egg (4h)
:OC_PopotoSalad: Popoto Salad (4h)
:OC_BoiledEgg: Boiled Egg (4h)
Schedule #2
:OC_PowderedPaprika: Powdered Paprika (4h)
:OC_CoconutJuice: Coconut Juice (4h)
:OC_PumpkinPudding: Pumpkin Pudding (6h)
:OC_CoconutJuice: Coconut Juice (4h)
:OC_PumpkinPudding: Pumpkin Pudding (6h)
Schedule #3
:OC_PopotoSalad: Popoto Salad (4h)
:OC_BoiledEgg: Boiled Egg (4h)
:OC_GrilledClam: Grilled Clam (4h)
:OC_IslefishPie: Pie (6h)
:OC_PumpkinPudding: Pumpkin Pudding (6h)
Schedule #4
:OC_BrassServingDish: Brass Serving Dish (4h)
:OC_IronAxe: Iron Axe (8h)
:OC_BrassServingDish: Brass Serving Dish (4h)
:OC_IronAxe: Iron Axe (8h)
Schedule #5
:OC_BrassServingDish: Brass Serving Dish (4h)
:OC_IronAxe: Iron Axe (8h)
:OC_BrassServingDish: Brass Serving Dish (4h)
:OC_IronAxe: Iron Axe (8h)
```

**Comment by Jaksuhn** [comment]
What version are you on? All of those import correctly for me. The importer doesn't care if it says Islefish Pie or just Pie

**Comment by ramblinguy** [comment]
Hmm I'm using v0.0.0.16, according to the plugin list. Actually I just realized, I was using `https://github.com/awgil/ffxiv_plugin_distribution/raw/master/pluginmaster.json` as the repo, which looks like it's outdated. Sorry about that! Let me try using `https://puni.sh/api/repository/veyn` as the repo and see if that works- it looks like it has 0.0.0.42

**Comment by ramblinguy** [comment]
Yep that worked, looks like the problem was between keyboard and chair 😅 thanks for looking into this!
