### ISSUE TITLE
"Unable to execute command while in flight" error

### ISSUE THREAD

**Issue by Flavescent** [awgil/ffxiv_visland#30]
If a gathering node is targeted for interaction while in flight, VIsland will sometimes keep the character hovering slightly above the node while continuing to cause the game to emit the error "Unable to execute command while in flight" (see images below). 

![image](https://github.com/awgil/ffxiv_visland/assets/12690771/3eec58c2-03e3-4056-b168-88423ec1b306)
![image](https://github.com/awgil/ffxiv_visland/assets/12690771/d205be04-34a4-4b9d-bfc7-68564f02614f)

This seems to happen more frequently if the node is approached from a steep angle. But this error is not always reproducible, as ordering the character to continue the loop from one step previously will sometimes cause the problematic interaction step to proceed as intended.

Is there a way to address this?

**Comment by Jaksuhn** [comment]
It's an issue with your route. Your hitbox is on the cliff next to the node where it cannot land. Either change the position or the radius of that waypoint. This might be addressable later with smarter nav but for now that's your solution
