### ISSUE TITLE
Feature request: Allow inserting a new step at an arbitrary position

### ISSUE THREAD

**Issue by Flavescent** [awgil/ffxiv_visland#31]
In long loops, if a step is found to be missing which causes the character to be stuck in the territory, it is tedious to have to create a new step at the end of the loop and to have to move it up to the desired position one click at a time. It would help if we could insert a new step at an arbitrary position in the loop. Thank you for this plugin!

**Comment by Jaksuhn** [comment]
added in #c9a04d4, v0.0.0.50
