### ISSUE TITLE
Feature Request: Check that Gather Mode is Enabled

### ISSUE THREAD

**Issue by KiwiMonkeyUSA** [awgil/ffxiv_visland#38]
Not sure if it is possible, but a feature to check that Gather mode is enabled would be most helpful. For those times when someone may accidentally activate a route but forget to turn Gather mode on. Currently, if route is enabled without gather mode enabled, character will simply run from node to node to node without doing anything.

**Comment by Jaksuhn** [comment]
added in [d3212a0](https://github.com/awgil/ffxiv_visland/commit/d3212a07e606a215dfafc32ac08468b850e5c8ef), v0.0.0.51
