### ISSUE TITLE
Failed to load (load error)

### ISSUE THREAD

**Issue by 99bluerabbit** [awgil/ffxiv_visland#40]
Since 01/01/2024 the plugin fails to load on startup. 
![image](https://github.com/awgil/ffxiv_visland/assets/43675643/246b57ba-addb-4f29-9da2-44be5c26d1d7)

Unsure what to do and how to fix, please advice.

**Comment by Jaksuhn** [comment]
switch your dalamud branch to release, they broke the staging version
