### ISSUE TITLE
Can no longer sow seeds in the garden

### ISSUE THREAD

**Issue by mjsalerno** [awgil/ffxiv_visland#42]
I used to be able to sow seeds in the garden but now when starting a route it forces the mode to be gather

**Comment by Jaksuhn** [comment]
yes because of #38 
just entrust them to the auto mammet?

**Comment by mjsalerno** [comment]
ya that is an option. is it possible to make #38 optional though? i prefer to not need to spend my cowries on the mammets :c

**Comment by mjsalerno** [comment]
thank you so much I really appreciate this. Do you have a ko-fi or any sort of donation thing set up? I will literally donate to you.

**Comment by Jaksuhn** [comment]
donate to veyn before me since it's mostly his work in this plugin: https://ko-fi.com/andrewgilewsky
