### ISSUE TITLE
loop with red "Loop Route" button

### ISSUE THREAD

**Issue by BlazeM13** [awgil/ffxiv_visland#44]
still loop when i checked the Loop Route to red

**Comment by Jaksuhn** [comment]
fixed

**Comment by BlazeM13** [comment]
still a problem when use command "/visland exec "

**Comment by Jaksuhn** [comment]
sorry I did the equivalent of basically putting the fix in without turning it on

now it should actually be fixed

**Comment by BlazeM13** [comment]
https://youtu.be/hPoWr77FE0A try it still loop when use command

**Comment by Jaksuhn** [comment]
... well that's not at what I thought this was about. That command isn't supposed to respect the loop button in the window
`exec` loops, `execonce` doesn't
