### ISSUE TITLE
Any Wait command (created via UI) after the first one executed in a loop is ignored

### ISSUE THREAD

**Issue by KHShadowrunner** [awgil/ffxiv_visland#45]
If you create a 3 point route, and add a "Toggle Wait" to all 3 points for any amount of time, when executing a loop only the first point will wait the toggled time, all other toggles are ignored. 

If you manually start the loop on any of the route marks - it respects the wait on that point for the first loop, then only triggers the first point again.

**Comment by KHShadowrunner** [comment]
Latest update sort of changed it. If I had to guess:
Now if any wait is longer than the first wait, it will wait for the difference between the first and the next.
An example:
Point 1: Wait set to 8646
Point 2: Wait set to 6563
Point 3: Wait set for 16146

It waits at 1 (For a little shorter than 8 seconds but I can live with that). Immediately skips 2 and waits at 3 for about 3 seconds.

**Comment by Jaksuhn** [comment]
fixed in v66, sorry for the wait (pun intended)
