### ISSUE TITLE
Route no longer stops looping after turning off Loop Route

### ISSUE THREAD

**Issue by thedoo** [awgil/ffxiv_visland#47]
Before, you could toggle on Loop Route and run the route and it would keep looping. When I was finished I could turn Loop Route off and it would finish the current loop it was on and end.

Now, if I turn off Loop Route after it was already active, the route still continues looping. The only way to end the route now is to hit stop.

**Comment by Jaksuhn** [comment]
that that was possible before wasn't really intended, and with the addition of running anonymous routes via command, there isn't really a good way of supporting that behaviour
