### ISSUE TITLE
Not really an issue but I could not find where to post it

### ISSUE THREAD

**Issue by mgrenier25** [awgil/ffxiv_visland#53]
Just a route I made for collecting the crops on the island, it might require some cleanup because some crops were not empty, also I run the game in french.
It can also be used for planting seeds or watering, just have to select the right action/items before running the route.

`{"Name":"Garden","Waypoints":[{"Position":{"X":-240.0,"Y":57.9,"Z":123.0},"ZoneID":0,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"parcelle","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-240.0,"Y":57.9,"Z":117.5},"ZoneID":0,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"parcelle","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-240.0,"Y":57.9,"Z":112.0},"ZoneID":0,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"parcelle","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-240.0,"Y":57.9,"Z":106.5},"ZoneID":0,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"parcelle","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-240.0,"Y":57.9,"Z":101.0},"ZoneID":0,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"parcelle","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-216.0,"Y":60.4,"Z":97.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"fraises exotiques","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-216.0,"Y":60.4,"Z":102.5},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"fraises exotiques","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-216.0,"Y":60.4,"Z":108.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"fraises exotiques","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-216.0,"Y":60.4,"Z":113.5},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"fraises exotiques","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-216.0,"Y":60.4,"Z":119.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"fraises exotiques","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-202.8011,"Y":62.010185,"Z":143.4368},"ZoneID":1055,"Radius":3.0,"Movement":0,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-188.12971,"Y":66.096436,"Z":133.77792},"ZoneID":1055,"Radius":3.0,"Movement":0,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-189.0,"Y":66.4,"Z":127.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de blé exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-189.0,"Y":66.4,"Z":121.5},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de blé exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-189.0,"Y":66.4,"Z":116.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de blé exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-189.0,"Y":66.4,"Z":110.5},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de blé exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-189.0,"Y":66.4,"Z":105.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de blé exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-179.0,"Y":66.4,"Z":105.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de maïs exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-179.0,"Y":66.4,"Z":110.5},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de maïs exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-179.0,"Y":66.4,"Z":116.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de maïs exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-179.0,"Y":66.4,"Z":121.5},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de maïs exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-179.0,"Y":66.4,"Z":127.0},"ZoneID":1055,"Radius":2.0,"Movement":0,"InteractWithOID":2013159,"InteractWithName":"épis de maïs exotique","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"showWaits":false,"WaitForCondition":0,"WaitTimeMs":0}]}`

**Comment by Jaksuhn** [comment]
thanks for the route! We've got a wiki you're more than welcome to add to if make anything else :)
I added yours for you this time.

https://github.com/awgil/ffxiv_visland/wiki/Island-Sanctuary-Routes
