### ISSUE TITLE
Newest update 240301 broke Automated Gathering

### ISSUE THREAD

**Issue by ghost** [awgil/ffxiv_visland#55]
Whatever was done with the update that was released today has totally borked Island Sanctuary in its entirety with gathering nodes. You can get set up with the proper route via the 'original paths' or the 'optimized paths'; it doesn't matter which one; 'hit start', and as soon as your character runs up to the node, the menu for Automated Gathering will disappear in its entirety, and the character will just stand there like a lump on the log doing nothing. But as soon as you manually pull the character away from the node it ran to, the menu will reappear and cause the character to run back to the node without any input from the player and continue to do nothing.

The plugin's Automated Gathering was working perfectly yesterday, as of 240229.

**Comment by Jaksuhn** [comment]
fixed
