### ISSUE TITLE
Failed to import route - Dawntrail routes

### ISSUE THREAD

**Issue by Sylphrena-Sedai** [awgil/ffxiv_visland#69]
When trying to import any of the Dawtntrail gathering routes I get:

``` Failed to import route: Unexpected character encountered while parsing value: H. Path '', line 0, position 0.```

**Comment by Artemyy** [comment]
Right click the import button when importing, not left. :) Check the discord in the future if you're having trouble, it usually solves my problems with a search

**Comment by Jaksuhn** [comment]
button now accepts both types without having to specify btw

**Comment by Sylphrena-Sedai** [comment]
Thanks! I didn't know there was a discord for this, could you share it please? 

> Right click the import button when importing, not left. :) Check the discord in the future if you're having trouble, it usually solves my problems with a search

I wasn't aware there was a discord for this, could you share it please? Thanks

**Comment by Sylphrena-Sedai** [comment]
> button now accepts both types without having to specify btw

Thanks!
