### ISSUE TITLE
Please add Raw Ihuykanite

### ISSUE THREAD

**Issue by ScarletL1995** [awgil/ffxiv_visland#70]
Already created everything you needed so you can share with others.

{"Name":"Raw Ihuykanite","Group":"Dawntrail Mining","Waypoints":[{"Position":{"X":-644.8648,"Y":1.356641,"Z":-415.7496},"ZoneID":1188,"Radius":3.0,"Movement":1,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-644.7781,"Y":2.261729,"Z":-416.9234},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34764,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-634.87604,"Y":2.4317012,"Z":-417.7401},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-632.9135,"Y":2.716663,"Z":-417.9657},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34764,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-630.439,"Y":2.4009845,"Z":-417.48648},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-628.5966,"Y":3.089153,"Z":-417.3812},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34763,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-623.82574,"Y":2.757052,"Z":-418.4196},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-621.8856,"Y":3.151928,"Z":-418.6934},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34764,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-585.5574,"Y":2.4047003,"Z":-227.83888},"ZoneID":1188,"Radius":3.0,"Movement":1,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-584.8643,"Y":3.320522,"Z":-227.3047},"ZoneID":1188,"Radius":20.0,"Movement":0,"Pathfind":true,"InteractWithOID":34762,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-592.9148,"Y":2.5115938,"Z":-224.75308},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-593.9269,"Y":3.169262,"Z":-223.1938},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34761,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-601.1419,"Y":2.43512,"Z":-218.27461},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-602.5651,"Y":3.251461,"Z":-217.1539},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34762,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-612.38617,"Y":1.3635416,"Z":-206.97226},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-613.296,"Y":2.557324,"Z":-205.7018},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34762,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-824.6856,"Y":8.510737,"Z":-281.66226},"ZoneID":1188,"Radius":3.0,"Movement":1,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-825.0306,"Y":9.265428,"Z":-279.9193},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34766,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-824.2456,"Y":8.187288,"Z":-309.9297},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-824.2916,"Y":8.34999,"Z":-311.9117},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34766,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-824.3267,"Y":7.678891,"Z":-325.87558},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-824.3366,"Y":7.884955,"Z":-327.8148},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34765,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-823.2802,"Y":7.2854614,"Z":-342.08203},"ZoneID":1188,"Radius":3.0,"Movement":0,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0},{"Position":{"X":-823.1537,"Y":7.570713,"Z":-344.0435},"ZoneID":1188,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":34766,"InteractWithName":"mineral deposit","showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0}]}

**Comment by Jaksuhn** [comment]
add it to the wiki, it's freely editable by everyone

**Comment by AirDur** [comment]
I added your path on wiki
