### ISSUE TITLE
[Suggestion] Allow Copy/Pasting Favors from OC

### ISSUE THREAD

**Issue by Polarthief** [awgil/ffxiv_visland#75]
I have a suggestion regarding taking the /favors command from Overseas Casuals'. When trying to paste it in, the plugin recognizes it as a 4 or 5-workshop agenda (the latter being impossible). It would be nice if there was simply an extra button for "Set This Week" and "Set Next Week" that had a description of "set each agenda below in Workshop 4 across a week", if that makes sense.

This would, in essence, allow you to still copy your normal Daily/Weekly recs into Workshops 1-3 but having better-value /favors for your 4th workshops. The experimental Favors solver from KD3's spreadsheet isn't bad, but the /favors command is a bit more personalized based on the week for higher cowrie values.

**Comment by Jaksuhn** [comment]
No plans to support it. Would require too much work changing the existing import to support it as well or would clutter the ui even further. We have the solver already, the difference in cowries is pretty minimal
