### ISSUE TITLE
[Add New Route] Botanist Route Dwarven Cotton Boll / Bomca Rice / Coffee Beans

### ISSUE THREAD

**Issue by ScarletL1995** [awgil/ffxiv_visland#82]
{"Name":"Dwarven Cotton Boll / Bomca Rice / Coffee Beans","Group":"Botanist (71 - 80)","Food":0,"Manual":0,"TargetGatherItem":0,"Waypoints":[{"Position":{"X":-463.98627,"Y":382.33093,"Z":-419.86383},"ZoneID":814,"Radius":3.0,"Movement":1,"Pathfind":true,"InteractWithOID":0,"InteractWithName":"","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":99,"IsNode":false,"NodeJob":0},{"Position":{"X":-477.6227,"Y":379.6245,"Z":-423.1174},"ZoneID":814,"Radius":2.0,"Movement":1,"Pathfind":true,"InteractWithOID":32762,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-461.3445,"Y":375.4309,"Z":-405.4238},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":false,"InteractWithOID":32762,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-454.49,"Y":375.2849,"Z":-407.9195},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":true,"InteractWithOID":32761,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-452.1707,"Y":374.2344,"Z":-400.412},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":true,"InteractWithOID":32762,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-433.4643,"Y":364.3049,"Z":-297.0565},"ZoneID":814,"Radius":2.0,"Movement":1,"Pathfind":true,"InteractWithOID":32760,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-434.8889,"Y":362.8084,"Z":-279.5544},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":true,"InteractWithOID":32760,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-415.8268,"Y":361.6699,"Z":-271.7809},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":true,"InteractWithOID":32760,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":true,"Interaction":0,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-410.7307,"Y":362.0156,"Z":-272.5378},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":true,"InteractWithOID":32759,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-311.9707,"Y":374.5285,"Z":-372.9458},"ZoneID":814,"Radius":2.0,"Movement":1,"Pathfind":false,"InteractWithOID":32764,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-298.7021,"Y":376.462,"Z":-381.3353},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":true,"InteractWithOID":32764,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-302.386,"Y":376.8885,"Z":-386.2368},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":true,"InteractWithOID":32764,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17},{"Position":{"X":-301.1088,"Y":377.6338,"Z":-390.8202},"ZoneID":814,"Radius":2.0,"Movement":0,"Pathfind":true,"InteractWithOID":32763,"InteractWithName":"lush vegetation patch","InteractWithPosition":{"X":0.0,"Y":0.0,"Z":0.0},"showInteractions":false,"Interaction":1,"EmoteID":0,"ItemID":0,"ActionID":0,"QuestID":0,"QuestSeq":0,"MobID":0,"StopCondition":0,"KillCount":0,"RouteName":"","ChatCommand":"","showWaits":false,"WaitForCondition":0,"WaitTimeMs":0,"WaitTimeET":{"X":0.0,"Y":0.0},"IsPhantom":false,"Path":null,"GatheringType":3,"IsNode":true,"NodeJob":17}]}

**Comment by ScarletL1995** [comment]
Not really an issue, I was submitting this so you can add it to your list to share with everyone.

**Comment by Jaksuhn** [comment]
Post to the wiki! It's freely editable by everyone
