### ISSUE TITLE
OC import stopped working.

### ISSUE THREAD

**Issue by github-1348A55** [awgil/ffxiv_visland#85]
OC import stopped working after the 7.1 update.
I'm playing FFXIV in Japanese, so I don't know if this is a language-specific issue,
but I didn't have any problems before 7.1
Does the current OC import function work fine in other languages?

**Comment by Jaksuhn** [comment]
it at least works fine in english

**Comment by github-1348A55** [comment]
> it at least works fine in english

Thank you for your reply.

When I changed the in-game language to English using the XIV launcher and launched the game,
the OC import worked, but when I changed it back to Japanese it didn't work.

Not sure about French, German, Chinese, Korean, etc,
but I decided to switch to English once a week.

**Comment by github-1348A55** [comment]
I've tried starting it in Deutsch and Français since then, but there was no response.
I still think that OC import is now English-only.
It probably does not work with Chinese or Korean clients either.
It may work again, e.g. with a future update of Dalamud, but I can't imagine when that will be...

**Comment by Jaksuhn** [comment]
I'll go back and check and see if there was something I overlooked during the update that caused this. I'll also leave the issue open since it wasn't intentional and it _should_ be working for all languages

**Comment by Jaksuhn** [comment]
works in other languages again

**Comment by github-1348A55** [comment]
> works in other languages again

Yay!!!
This week I switched to English and used OC import.
Next week I won't need to switch languages.
Thanks Jaksuhn for the fix!
